//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fam3 {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class efx_ico {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal efx_ico() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fam3.efx_ico", typeof(efx_ico).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		public static System.Drawing.Bitmap asm {
			get {
				object obj = ResourceManager.GetObject("asm", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap blue_diamond {
			get {
				object obj = ResourceManager.GetObject("blue-diamond", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap Blue_Soap_16x16 {
			get {
				object obj = ResourceManager.GetObject("Blue-Soap-16x16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Icon book {
			get {
				object obj = ResourceManager.GetObject("book", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		public static System.Drawing.Bitmap box_diamond {
			get {
				object obj = ResourceManager.GetObject("box-diamond", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap box_TPL {
			get {
				object obj = ResourceManager.GetObject("box_TPL", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap boxB0 {
			get {
				object obj = ResourceManager.GetObject("boxB0", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap boxB012 {
			get {
				object obj = ResourceManager.GetObject("boxB012", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap boxC {
			get {
				object obj = ResourceManager.GetObject("boxC", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap boxG {
			get {
				object obj = ResourceManager.GetObject("boxG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap boxGold {
			get {
				object obj = ResourceManager.GetObject("boxGold", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap boxGray {
			get {
				object obj = ResourceManager.GetObject("boxGray", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap boxM {
			get {
				object obj = ResourceManager.GetObject("boxM", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap boxOrange {
			get {
				object obj = ResourceManager.GetObject("boxOrange", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap boxR {
			get {
				object obj = ResourceManager.GetObject("boxR", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap boxY {
			get {
				object obj = ResourceManager.GetObject("boxY", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap class_object_ymc {
			get {
				object obj = ResourceManager.GetObject("class-object-ymc", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap class_object_yrb {
			get {
				object obj = ResourceManager.GetObject("class-object-yrb", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap class_old {
			get {
				object obj = ResourceManager.GetObject("class-old", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Icon csico {
			get {
				object obj = ResourceManager.GetObject("csico", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		public static System.Drawing.Icon csico3 {
			get {
				object obj = ResourceManager.GetObject("csico3", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		public static System.Drawing.Icon csmf {
			get {
				object obj = ResourceManager.GetObject("csmf", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		public static System.Drawing.Bitmap curly_right {
			get {
				object obj = ResourceManager.GetObject("curly-right", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Icon efx_36 {
			get {
				object obj = ResourceManager.GetObject("efx_36", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		public static System.Drawing.Icon efx_doc {
			get {
				object obj = ResourceManager.GetObject("efx_doc", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		public static System.Drawing.Bitmap enumeration {
			get {
				object obj = ResourceManager.GetObject("enumeration", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap field {
			get {
				object obj = ResourceManager.GetObject("field", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Icon flaico {
			get {
				object obj = ResourceManager.GetObject("flaico", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		public static System.Drawing.Bitmap fugue_folder_assemblies {
			get {
				object obj = ResourceManager.GetObject("fugue-folder-assemblies", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap fx_text0 {
			get {
				object obj = ResourceManager.GetObject("fx_text0", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap Golden_Binoculars_16x16 {
			get {
				object obj = ResourceManager.GetObject("Golden-Binoculars-16x16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap Light_Grey_Gear_16x16 {
			get {
				object obj = ResourceManager.GetObject("Light-Grey-Gear-16x16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap Magnifying_Glass_16x16 {
			get {
				object obj = ResourceManager.GetObject("Magnifying-Glass-16x16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap manhatton_Asymmetrical_Glue {
			get {
				object obj = ResourceManager.GetObject("manhatton_Asymmetrical-Glue", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap manhatton_buff_fingerpointer {
			get {
				object obj = ResourceManager.GetObject("manhatton_buff_fingerpointer", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap methodC {
			get {
				object obj = ResourceManager.GetObject("methodC", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap methodG {
			get {
				object obj = ResourceManager.GetObject("methodG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap methodM {
			get {
				object obj = ResourceManager.GetObject("methodM", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap methodMx {
			get {
				object obj = ResourceManager.GetObject("methodMx", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap path8556 {
			get {
				object obj = ResourceManager.GetObject("path8556", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Icon pencilico {
			get {
				object obj = ResourceManager.GetObject("pencilico", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		public static System.Drawing.Icon pow_icon {
			get {
				object obj = ResourceManager.GetObject("pow_icon", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		public static System.Drawing.Bitmap ref_asm {
			get {
				object obj = ResourceManager.GetObject("ref_asm", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap ref_asmDir {
			get {
				object obj = ResourceManager.GetObject("ref_asmDir", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap ref_enum {
			get {
				object obj = ResourceManager.GetObject("ref_enum", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap ref_ns {
			get {
				object obj = ResourceManager.GetObject("ref_ns", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap ref_obj {
			get {
				object obj = ResourceManager.GetObject("ref_obj", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap refAssembly {
			get {
				object obj = ResourceManager.GetObject("refAssembly", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap rimshotdesign_font {
			get {
				object obj = ResourceManager.GetObject("rimshotdesign_font", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Icon Sci48M {
			get {
				object obj = ResourceManager.GetObject("Sci48M", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		public static System.Drawing.Icon SciBall {
			get {
				object obj = ResourceManager.GetObject("SciBall", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		public static System.Drawing.Bitmap Stickies_16x16 {
			get {
				object obj = ResourceManager.GetObject("Stickies-16x16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap Tube_with_stuff_in_it_16x16 {
			get {
				object obj = ResourceManager.GetObject("Tube-with-stuff-in-it-16x16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap Tube_with_stuff_in_it_48x48 {
			get {
				object obj = ResourceManager.GetObject("Tube-with-stuff-in-it-48x48", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap X_Icon_Gray {
			get {
				object obj = ResourceManager.GetObject("X_Icon_Gray", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap X_Icon_red {
			get {
				object obj = ResourceManager.GetObject("X_Icon_red", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
