//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fam3 {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class famfam_mini {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal famfam_mini() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fam3.famfam_mini", typeof(famfam_mini).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		public static System.Drawing.Bitmap action_back {
			get {
				object obj = ResourceManager.GetObject("action_back", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap action_forward {
			get {
				object obj = ResourceManager.GetObject("action_forward", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap action_go {
			get {
				object obj = ResourceManager.GetObject("action_go", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap action_paste {
			get {
				object obj = ResourceManager.GetObject("action_paste", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap action_print {
			get {
				object obj = ResourceManager.GetObject("action_print", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap action_refresh {
			get {
				object obj = ResourceManager.GetObject("action_refresh", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap action_refresh_blue {
			get {
				object obj = ResourceManager.GetObject("action_refresh_blue", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap action_save {
			get {
				object obj = ResourceManager.GetObject("action_save", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap action_stop {
			get {
				object obj = ResourceManager.GetObject("action_stop", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap application_dreamweaver {
			get {
				object obj = ResourceManager.GetObject("application_dreamweaver", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap application_firefox {
			get {
				object obj = ResourceManager.GetObject("application_firefox", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap application_flash {
			get {
				object obj = ResourceManager.GetObject("application_flash", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_down {
			get {
				object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_left {
			get {
				object obj = ResourceManager.GetObject("arrow_left", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_right {
			get {
				object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_up {
			get {
				object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap box {
			get {
				object obj = ResourceManager.GetObject("box", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap calendar {
			get {
				object obj = ResourceManager.GetObject("calendar", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap comment {
			get {
				object obj = ResourceManager.GetObject("comment", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap comment_blue {
			get {
				object obj = ResourceManager.GetObject("comment_blue", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap comment_delete {
			get {
				object obj = ResourceManager.GetObject("comment_delete", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap comment_new {
			get {
				object obj = ResourceManager.GetObject("comment_new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap comment_yellow {
			get {
				object obj = ResourceManager.GetObject("comment_yellow", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap copy {
			get {
				object obj = ResourceManager.GetObject("copy", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap cut {
			get {
				object obj = ResourceManager.GetObject("cut", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap date {
			get {
				object obj = ResourceManager.GetObject("date", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap date_delete {
			get {
				object obj = ResourceManager.GetObject("date_delete", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap date_new {
			get {
				object obj = ResourceManager.GetObject("date_new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap file_acrobat {
			get {
				object obj = ResourceManager.GetObject("file_acrobat", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap file_font {
			get {
				object obj = ResourceManager.GetObject("file_font", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap file_font_truetype {
			get {
				object obj = ResourceManager.GetObject("file_font_truetype", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap flag_blue {
			get {
				object obj = ResourceManager.GetObject("flag_blue", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap flag_green {
			get {
				object obj = ResourceManager.GetObject("flag_green", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap flag_orange {
			get {
				object obj = ResourceManager.GetObject("flag_orange", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap flag_red {
			get {
				object obj = ResourceManager.GetObject("flag_red", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap flag_white {
			get {
				object obj = ResourceManager.GetObject("flag_white", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder {
			get {
				object obj = ResourceManager.GetObject("folder", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_delete {
			get {
				object obj = ResourceManager.GetObject("folder_delete", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_images {
			get {
				object obj = ResourceManager.GetObject("folder_images", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_lock {
			get {
				object obj = ResourceManager.GetObject("folder_lock", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_new {
			get {
				object obj = ResourceManager.GetObject("folder_new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_page {
			get {
				object obj = ResourceManager.GetObject("folder_page", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_accept {
			get {
				object obj = ResourceManager.GetObject("icon_accept", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_airmail {
			get {
				object obj = ResourceManager.GetObject("icon_airmail", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_alert {
			get {
				object obj = ResourceManager.GetObject("icon_alert", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_attachment {
			get {
				object obj = ResourceManager.GetObject("icon_attachment", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_clock {
			get {
				object obj = ResourceManager.GetObject("icon_clock", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_component {
			get {
				object obj = ResourceManager.GetObject("icon_component", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_download {
			get {
				object obj = ResourceManager.GetObject("icon_download", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_email {
			get {
				object obj = ResourceManager.GetObject("icon_email", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_extension {
			get {
				object obj = ResourceManager.GetObject("icon_extension", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_favourites {
			get {
				object obj = ResourceManager.GetObject("icon_favourites", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_get_world {
			get {
				object obj = ResourceManager.GetObject("icon_get_world", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_history {
			get {
				object obj = ResourceManager.GetObject("icon_history", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_home {
			get {
				object obj = ResourceManager.GetObject("icon_home", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_info {
			get {
				object obj = ResourceManager.GetObject("icon_info", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_key {
			get {
				object obj = ResourceManager.GetObject("icon_key", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_link {
			get {
				object obj = ResourceManager.GetObject("icon_link", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_mail {
			get {
				object obj = ResourceManager.GetObject("icon_mail", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_monitor_mac {
			get {
				object obj = ResourceManager.GetObject("icon_monitor_mac", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_monitor_pc {
			get {
				object obj = ResourceManager.GetObject("icon_monitor_pc", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_network {
			get {
				object obj = ResourceManager.GetObject("icon_network", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_package {
			get {
				object obj = ResourceManager.GetObject("icon_package", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_package_get {
			get {
				object obj = ResourceManager.GetObject("icon_package_get", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_package_open {
			get {
				object obj = ResourceManager.GetObject("icon_package_open", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_padlock {
			get {
				object obj = ResourceManager.GetObject("icon_padlock", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_security {
			get {
				object obj = ResourceManager.GetObject("icon_security", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_settings {
			get {
				object obj = ResourceManager.GetObject("icon_settings", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_user {
			get {
				object obj = ResourceManager.GetObject("icon_user", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_wand {
			get {
				object obj = ResourceManager.GetObject("icon_wand", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_world {
			get {
				object obj = ResourceManager.GetObject("icon_world", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap icon_world_dynamic {
			get {
				object obj = ResourceManager.GetObject("icon_world_dynamic", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap image {
			get {
				object obj = ResourceManager.GetObject("image", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap image_new {
			get {
				object obj = ResourceManager.GetObject("image_new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap interface_browser {
			get {
				object obj = ResourceManager.GetObject("interface_browser", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap interface_dialog {
			get {
				object obj = ResourceManager.GetObject("interface_dialog", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap interface_installer {
			get {
				object obj = ResourceManager.GetObject("interface_installer", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap list_comments {
			get {
				object obj = ResourceManager.GetObject("list_comments", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap list_components {
			get {
				object obj = ResourceManager.GetObject("list_components", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap list_errors {
			get {
				object obj = ResourceManager.GetObject("list_errors", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap list_extensions {
			get {
				object obj = ResourceManager.GetObject("list_extensions", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap list_images {
			get {
				object obj = ResourceManager.GetObject("list_images", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap list_keys {
			get {
				object obj = ResourceManager.GetObject("list_keys", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap list_links {
			get {
				object obj = ResourceManager.GetObject("list_links", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap list_packages {
			get {
				object obj = ResourceManager.GetObject("list_packages", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap list_security {
			get {
				object obj = ResourceManager.GetObject("list_security", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap list_settings {
			get {
				object obj = ResourceManager.GetObject("list_settings", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap list_users {
			get {
				object obj = ResourceManager.GetObject("list_users", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap list_world {
			get {
				object obj = ResourceManager.GetObject("list_world", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap note {
			get {
				object obj = ResourceManager.GetObject("note", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap note_delete {
			get {
				object obj = ResourceManager.GetObject("note_delete", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap note_new {
			get {
				object obj = ResourceManager.GetObject("note_new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page {
			get {
				object obj = ResourceManager.GetObject("page", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_alert {
			get {
				object obj = ResourceManager.GetObject("page_alert", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_attachment {
			get {
				object obj = ResourceManager.GetObject("page_attachment", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_bookmark {
			get {
				object obj = ResourceManager.GetObject("page_bookmark", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_boy {
			get {
				object obj = ResourceManager.GetObject("page_boy", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_code {
			get {
				object obj = ResourceManager.GetObject("page_code", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_colors {
			get {
				object obj = ResourceManager.GetObject("page_colors", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_component {
			get {
				object obj = ResourceManager.GetObject("page_component", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_cross {
			get {
				object obj = ResourceManager.GetObject("page_cross", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_delete {
			get {
				object obj = ResourceManager.GetObject("page_delete", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_deny {
			get {
				object obj = ResourceManager.GetObject("page_deny", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_down {
			get {
				object obj = ResourceManager.GetObject("page_down", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_dynamic {
			get {
				object obj = ResourceManager.GetObject("page_dynamic", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_edit {
			get {
				object obj = ResourceManager.GetObject("page_edit", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_extension {
			get {
				object obj = ResourceManager.GetObject("page_extension", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_favourites {
			get {
				object obj = ResourceManager.GetObject("page_favourites", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_find {
			get {
				object obj = ResourceManager.GetObject("page_find", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_flash {
			get {
				object obj = ResourceManager.GetObject("page_flash", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_girl {
			get {
				object obj = ResourceManager.GetObject("page_girl", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_html {
			get {
				object obj = ResourceManager.GetObject("page_html", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_java {
			get {
				object obj = ResourceManager.GetObject("page_java", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_key {
			get {
				object obj = ResourceManager.GetObject("page_key", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_left {
			get {
				object obj = ResourceManager.GetObject("page_left", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_link {
			get {
				object obj = ResourceManager.GetObject("page_link", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_lock {
			get {
				object obj = ResourceManager.GetObject("page_lock", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_new {
			get {
				object obj = ResourceManager.GetObject("page_new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_next {
			get {
				object obj = ResourceManager.GetObject("page_next", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_package {
			get {
				object obj = ResourceManager.GetObject("page_package", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_php {
			get {
				object obj = ResourceManager.GetObject("page_php", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_prev {
			get {
				object obj = ResourceManager.GetObject("page_prev", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_refresh {
			get {
				object obj = ResourceManager.GetObject("page_refresh", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_right {
			get {
				object obj = ResourceManager.GetObject("page_right", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_script {
			get {
				object obj = ResourceManager.GetObject("page_script", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_security {
			get {
				object obj = ResourceManager.GetObject("page_security", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_settings {
			get {
				object obj = ResourceManager.GetObject("page_settings", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_sound {
			get {
				object obj = ResourceManager.GetObject("page_sound", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_tag_blue {
			get {
				object obj = ResourceManager.GetObject("page_tag_blue", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_tag_red {
			get {
				object obj = ResourceManager.GetObject("page_tag_red", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_text {
			get {
				object obj = ResourceManager.GetObject("page_text", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_text_delete {
			get {
				object obj = ResourceManager.GetObject("page_text_delete", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_tick {
			get {
				object obj = ResourceManager.GetObject("page_tick", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_tree {
			get {
				object obj = ResourceManager.GetObject("page_tree", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_up {
			get {
				object obj = ResourceManager.GetObject("page_up", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_url {
			get {
				object obj = ResourceManager.GetObject("page_url", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_user {
			get {
				object obj = ResourceManager.GetObject("page_user", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_user_dark {
			get {
				object obj = ResourceManager.GetObject("page_user_dark", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_user_light {
			get {
				object obj = ResourceManager.GetObject("page_user_light", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_video {
			get {
				object obj = ResourceManager.GetObject("page_video", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap page_wizard {
			get {
				object obj = ResourceManager.GetObject("page_wizard", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static byte[] readme {
			get {
				object obj = ResourceManager.GetObject("readme", resourceCulture);
				return ((byte[])(obj));
			}
		}
		
		public static System.Drawing.Bitmap table {
			get {
				object obj = ResourceManager.GetObject("table", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap table_delete {
			get {
				object obj = ResourceManager.GetObject("table_delete", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap tables {
			get {
				object obj = ResourceManager.GetObject("tables", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
