//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fam3 {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class glyfx_vista {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal glyfx_vista() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fam3.glyfx_vista", typeof(glyfx_vista).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		public static System.Drawing.Bitmap arrow_left_16 {
			get {
				object obj = ResourceManager.GetObject("arrow_left_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_left_16_d {
			get {
				object obj = ResourceManager.GetObject("arrow_left_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_left_16_h {
			get {
				object obj = ResourceManager.GetObject("arrow_left_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_right_16 {
			get {
				object obj = ResourceManager.GetObject("arrow_right_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_right_16_d {
			get {
				object obj = ResourceManager.GetObject("arrow_right_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_right_16_h {
			get {
				object obj = ResourceManager.GetObject("arrow_right_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap clipboard_copy_lined_16 {
			get {
				object obj = ResourceManager.GetObject("clipboard_copy_lined_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap clipboard_copy_lined_16_d {
			get {
				object obj = ResourceManager.GetObject("clipboard_copy_lined_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap clipboard_copy_lined_16_h {
			get {
				object obj = ResourceManager.GetObject("clipboard_copy_lined_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap clipboard_copy_unlined_16 {
			get {
				object obj = ResourceManager.GetObject("clipboard_copy_unlined_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap clipboard_copy_unlined_16_d {
			get {
				object obj = ResourceManager.GetObject("clipboard_copy_unlined_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap clipboard_copy_unlined_16_h {
			get {
				object obj = ResourceManager.GetObject("clipboard_copy_unlined_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap clipboard_cut_16 {
			get {
				object obj = ResourceManager.GetObject("clipboard_cut_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap clipboard_cut_16_d {
			get {
				object obj = ResourceManager.GetObject("clipboard_cut_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap clipboard_cut_16_h {
			get {
				object obj = ResourceManager.GetObject("clipboard_cut_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap clipboard_paste_lined_16 {
			get {
				object obj = ResourceManager.GetObject("clipboard_paste_lined_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap clipboard_paste_lined_16_d {
			get {
				object obj = ResourceManager.GetObject("clipboard_paste_lined_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap clipboard_paste_lined_16_h {
			get {
				object obj = ResourceManager.GetObject("clipboard_paste_lined_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap clipboard_paste_unlined_16 {
			get {
				object obj = ResourceManager.GetObject("clipboard_paste_unlined_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap clipboard_paste_unlined_16_d {
			get {
				object obj = ResourceManager.GetObject("clipboard_paste_unlined_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap clipboard_paste_unlined_16_h {
			get {
				object obj = ResourceManager.GetObject("clipboard_paste_unlined_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap delete_16 {
			get {
				object obj = ResourceManager.GetObject("delete_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap delete_16_d {
			get {
				object obj = ResourceManager.GetObject("delete_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap delete_16_h {
			get {
				object obj = ResourceManager.GetObject("delete_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_new_lined_16 {
			get {
				object obj = ResourceManager.GetObject("document_new_lined_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_new_lined_16_d {
			get {
				object obj = ResourceManager.GetObject("document_new_lined_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_new_lined_16_h {
			get {
				object obj = ResourceManager.GetObject("document_new_lined_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_new_unlined_16 {
			get {
				object obj = ResourceManager.GetObject("document_new_unlined_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_new_unlined_16_d {
			get {
				object obj = ResourceManager.GetObject("document_new_unlined_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_new_unlined_16_h {
			get {
				object obj = ResourceManager.GetObject("document_new_unlined_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_open_16 {
			get {
				object obj = ResourceManager.GetObject("document_open_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_open_16_d {
			get {
				object obj = ResourceManager.GetObject("document_open_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_open_16_h {
			get {
				object obj = ResourceManager.GetObject("document_open_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_properties_lined_round_16 {
			get {
				object obj = ResourceManager.GetObject("document_properties_lined_round_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_properties_lined_round_16_d {
			get {
				object obj = ResourceManager.GetObject("document_properties_lined_round_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_properties_lined_round_16_h {
			get {
				object obj = ResourceManager.GetObject("document_properties_lined_round_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_properties_lined_square_16 {
			get {
				object obj = ResourceManager.GetObject("document_properties_lined_square_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_properties_lined_square_16_d {
			get {
				object obj = ResourceManager.GetObject("document_properties_lined_square_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_properties_lined_square_16_h {
			get {
				object obj = ResourceManager.GetObject("document_properties_lined_square_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_properties_unlined_round_16 {
			get {
				object obj = ResourceManager.GetObject("document_properties_unlined_round_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_properties_unlined_round_16_d {
			get {
				object obj = ResourceManager.GetObject("document_properties_unlined_round_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_properties_unlined_round_16_h {
			get {
				object obj = ResourceManager.GetObject("document_properties_unlined_round_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_properties_unlined_square_16 {
			get {
				object obj = ResourceManager.GetObject("document_properties_unlined_square_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_properties_unlined_square_16_d {
			get {
				object obj = ResourceManager.GetObject("document_properties_unlined_square_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_properties_unlined_square_16_h {
			get {
				object obj = ResourceManager.GetObject("document_properties_unlined_square_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_refresh_16 {
			get {
				object obj = ResourceManager.GetObject("document_refresh_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_refresh_16_d {
			get {
				object obj = ResourceManager.GetObject("document_refresh_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_refresh_16_h {
			get {
				object obj = ResourceManager.GetObject("document_refresh_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap favourites_16 {
			get {
				object obj = ResourceManager.GetObject("favourites_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap favourites_16_d {
			get {
				object obj = ResourceManager.GetObject("favourites_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap favourites_16_h {
			get {
				object obj = ResourceManager.GetObject("favourites_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_closed_16 {
			get {
				object obj = ResourceManager.GetObject("folder_closed_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_closed_16_d {
			get {
				object obj = ResourceManager.GetObject("folder_closed_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_closed_16_h {
			get {
				object obj = ResourceManager.GetObject("folder_closed_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_copy_to_16 {
			get {
				object obj = ResourceManager.GetObject("folder_copy_to_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_copy_to_16_d {
			get {
				object obj = ResourceManager.GetObject("folder_copy_to_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_copy_to_16_h {
			get {
				object obj = ResourceManager.GetObject("folder_copy_to_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_move_to_16 {
			get {
				object obj = ResourceManager.GetObject("folder_move_to_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_move_to_16_d {
			get {
				object obj = ResourceManager.GetObject("folder_move_to_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_move_to_16_h {
			get {
				object obj = ResourceManager.GetObject("folder_move_to_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_open_16 {
			get {
				object obj = ResourceManager.GetObject("folder_open_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_open_16_d {
			get {
				object obj = ResourceManager.GetObject("folder_open_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_open_16_h {
			get {
				object obj = ResourceManager.GetObject("folder_open_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_options_round_16 {
			get {
				object obj = ResourceManager.GetObject("folder_options_round_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_options_round_16_d {
			get {
				object obj = ResourceManager.GetObject("folder_options_round_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_options_round_16_h {
			get {
				object obj = ResourceManager.GetObject("folder_options_round_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_options_square_16 {
			get {
				object obj = ResourceManager.GetObject("folder_options_square_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_options_square_16_d {
			get {
				object obj = ResourceManager.GetObject("folder_options_square_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_options_square_16_h {
			get {
				object obj = ResourceManager.GetObject("folder_options_square_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_up_16 {
			get {
				object obj = ResourceManager.GetObject("folder_up_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_up_16_d {
			get {
				object obj = ResourceManager.GetObject("folder_up_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_up_16_h {
			get {
				object obj = ResourceManager.GetObject("folder_up_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folders_16 {
			get {
				object obj = ResourceManager.GetObject("folders_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folders_16_d {
			get {
				object obj = ResourceManager.GetObject("folders_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folders_16_h {
			get {
				object obj = ResourceManager.GetObject("folders_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap history_dark_a_16 {
			get {
				object obj = ResourceManager.GetObject("history_dark_a_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap history_dark_a_16_d {
			get {
				object obj = ResourceManager.GetObject("history_dark_a_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap history_dark_a_16_h {
			get {
				object obj = ResourceManager.GetObject("history_dark_a_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap history_dark_b_16 {
			get {
				object obj = ResourceManager.GetObject("history_dark_b_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap history_dark_b_16_d {
			get {
				object obj = ResourceManager.GetObject("history_dark_b_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap history_dark_b_16_h {
			get {
				object obj = ResourceManager.GetObject("history_dark_b_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap history_light_a_16 {
			get {
				object obj = ResourceManager.GetObject("history_light_a_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap history_light_a_16_d {
			get {
				object obj = ResourceManager.GetObject("history_light_a_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap history_light_a_16_h {
			get {
				object obj = ResourceManager.GetObject("history_light_a_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap history_light_b_16 {
			get {
				object obj = ResourceManager.GetObject("history_light_b_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap history_light_b_16_d {
			get {
				object obj = ResourceManager.GetObject("history_light_b_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap history_light_b_16_h {
			get {
				object obj = ResourceManager.GetObject("history_light_b_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap home_16 {
			get {
				object obj = ResourceManager.GetObject("home_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap home_16_d {
			get {
				object obj = ResourceManager.GetObject("home_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap home_16_h {
			get {
				object obj = ResourceManager.GetObject("home_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap mail_a_16 {
			get {
				object obj = ResourceManager.GetObject("mail_a_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap mail_a_16_d {
			get {
				object obj = ResourceManager.GetObject("mail_a_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap mail_a_16_h {
			get {
				object obj = ResourceManager.GetObject("mail_a_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap mail_b_16 {
			get {
				object obj = ResourceManager.GetObject("mail_b_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap mail_b_16_d {
			get {
				object obj = ResourceManager.GetObject("mail_b_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap mail_b_16_h {
			get {
				object obj = ResourceManager.GetObject("mail_b_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap print_16 {
			get {
				object obj = ResourceManager.GetObject("print_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap print_16_d {
			get {
				object obj = ResourceManager.GetObject("print_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap print_16_h {
			get {
				object obj = ResourceManager.GetObject("print_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap print_preview_lined_16 {
			get {
				object obj = ResourceManager.GetObject("print_preview_lined_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap print_preview_lined_16_d {
			get {
				object obj = ResourceManager.GetObject("print_preview_lined_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap print_preview_lined_16_h {
			get {
				object obj = ResourceManager.GetObject("print_preview_lined_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap print_preview_unlined_16 {
			get {
				object obj = ResourceManager.GetObject("print_preview_unlined_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap print_preview_unlined_16_d {
			get {
				object obj = ResourceManager.GetObject("print_preview_unlined_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap print_preview_unlined_16_h {
			get {
				object obj = ResourceManager.GetObject("print_preview_unlined_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap redo_round_16 {
			get {
				object obj = ResourceManager.GetObject("redo_round_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap redo_round_16_d {
			get {
				object obj = ResourceManager.GetObject("redo_round_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap redo_round_16_h {
			get {
				object obj = ResourceManager.GetObject("redo_round_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap redo_square_16 {
			get {
				object obj = ResourceManager.GetObject("redo_square_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap redo_square_16_d {
			get {
				object obj = ResourceManager.GetObject("redo_square_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap redo_square_16_h {
			get {
				object obj = ResourceManager.GetObject("redo_square_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap save_16 {
			get {
				object obj = ResourceManager.GetObject("save_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap save_16_d {
			get {
				object obj = ResourceManager.GetObject("save_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap save_16_h {
			get {
				object obj = ResourceManager.GetObject("save_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap search_16 {
			get {
				object obj = ResourceManager.GetObject("search_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap search_16_d {
			get {
				object obj = ResourceManager.GetObject("search_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap search_16_h {
			get {
				object obj = ResourceManager.GetObject("search_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap stop_16 {
			get {
				object obj = ResourceManager.GetObject("stop_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap stop_16_d {
			get {
				object obj = ResourceManager.GetObject("stop_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap stop_16_h {
			get {
				object obj = ResourceManager.GetObject("stop_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap undo_round_16 {
			get {
				object obj = ResourceManager.GetObject("undo_round_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap undo_round_16_d {
			get {
				object obj = ResourceManager.GetObject("undo_round_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap undo_round_16_h {
			get {
				object obj = ResourceManager.GetObject("undo_round_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap undo_square_16 {
			get {
				object obj = ResourceManager.GetObject("undo_square_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap undo_square_16_d {
			get {
				object obj = ResourceManager.GetObject("undo_square_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap undo_square_16_h {
			get {
				object obj = ResourceManager.GetObject("undo_square_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap view_16 {
			get {
				object obj = ResourceManager.GetObject("view_16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap view_16_d {
			get {
				object obj = ResourceManager.GetObject("view_16_d", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap view_16_h {
			get {
				object obj = ResourceManager.GetObject("view_16_h", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
