//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fam3 {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class sm {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal sm() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fam3.sm", typeof(sm).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		public static System.Drawing.Bitmap _16xIconFla_inkskape {
			get {
				object obj = ResourceManager.GetObject("16xIconFla.inkskape", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap _7zIco {
			get {
				object obj = ResourceManager.GetObject("7zIco", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_left_cyan {
			get {
				object obj = ResourceManager.GetObject("arrow_left_cyan", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_left_green {
			get {
				object obj = ResourceManager.GetObject("arrow_left_green", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_left_green2 {
			get {
				object obj = ResourceManager.GetObject("arrow_left_green2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_left_magenta {
			get {
				object obj = ResourceManager.GetObject("arrow_left_magenta", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_left_orange {
			get {
				object obj = ResourceManager.GetObject("arrow_left_orange", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_left_purple {
			get {
				object obj = ResourceManager.GetObject("arrow_left_purple", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_left_red {
			get {
				object obj = ResourceManager.GetObject("arrow_left_red", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_right_cyan {
			get {
				object obj = ResourceManager.GetObject("arrow_right_cyan", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_right_green {
			get {
				object obj = ResourceManager.GetObject("arrow_right_green", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_right_green2 {
			get {
				object obj = ResourceManager.GetObject("arrow_right_green2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_right_magenta {
			get {
				object obj = ResourceManager.GetObject("arrow_right_magenta", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_right_orange {
			get {
				object obj = ResourceManager.GetObject("arrow_right_orange", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_right_purple {
			get {
				object obj = ResourceManager.GetObject("arrow_right_purple", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap arrow_right_red {
			get {
				object obj = ResourceManager.GetObject("arrow_right_red", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap canvas {
			get {
				object obj = ResourceManager.GetObject("canvas", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap dr_arrow_cur {
			get {
				object obj = ResourceManager.GetObject("dr_arrow_cur", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap eraser_pink_cur {
			get {
				object obj = ResourceManager.GetObject("eraser_pink_cur", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder {
			get {
				object obj = ResourceManager.GetObject("folder", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap imgfile {
			get {
				object obj = ResourceManager.GetObject("imgfile", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap mid_16x {
			get {
				object obj = ResourceManager.GetObject("mid_16x", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap pencil_blue_cur {
			get {
				object obj = ResourceManager.GetObject("pencil_blue_cur", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap pencil_brush {
			get {
				object obj = ResourceManager.GetObject("pencil_brush", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap plugin {
			get {
				object obj = ResourceManager.GetObject("plugin", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap untitledproperty {
			get {
				object obj = ResourceManager.GetObject("untitledproperty", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
