//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fam3 {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class tango_emblems {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal tango_emblems() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fam3.tango_emblems", typeof(tango_emblems).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		public static System.Drawing.Bitmap emblem_favorite {
			get {
				object obj = ResourceManager.GetObject("emblem-favorite", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap emblem_important {
			get {
				object obj = ResourceManager.GetObject("emblem-important", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap emblem_photos {
			get {
				object obj = ResourceManager.GetObject("emblem-photos", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap emblem_readonly {
			get {
				object obj = ResourceManager.GetObject("emblem-readonly", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap emblem_symbolic_link {
			get {
				object obj = ResourceManager.GetObject("emblem-symbolic-link", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap emblem_system {
			get {
				object obj = ResourceManager.GetObject("emblem-system", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap emblem_unreadable {
			get {
				object obj = ResourceManager.GetObject("emblem-unreadable", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
