//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cor3 {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class tango_status {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal tango_status() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cor3.tango_status", typeof(tango_status).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		public static System.Drawing.Bitmap audio_volume_high {
			get {
				object obj = ResourceManager.GetObject("audio-volume-high", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap audio_volume_low {
			get {
				object obj = ResourceManager.GetObject("audio-volume-low", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap audio_volume_medium {
			get {
				object obj = ResourceManager.GetObject("audio-volume-medium", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap audio_volume_muted {
			get {
				object obj = ResourceManager.GetObject("audio-volume-muted", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap battery_caution {
			get {
				object obj = ResourceManager.GetObject("battery-caution", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap dialog_error {
			get {
				object obj = ResourceManager.GetObject("dialog-error", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap dialog_information {
			get {
				object obj = ResourceManager.GetObject("dialog-information", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap dialog_warning {
			get {
				object obj = ResourceManager.GetObject("dialog-warning", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_drag_accept {
			get {
				object obj = ResourceManager.GetObject("folder-drag-accept", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_open {
			get {
				object obj = ResourceManager.GetObject("folder-open", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_visiting {
			get {
				object obj = ResourceManager.GetObject("folder-visiting", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap image_loading {
			get {
				object obj = ResourceManager.GetObject("image-loading", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap image_missing {
			get {
				object obj = ResourceManager.GetObject("image-missing", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap mail_attachment {
			get {
				object obj = ResourceManager.GetObject("mail-attachment", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap network_error {
			get {
				object obj = ResourceManager.GetObject("network-error", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap network_idle {
			get {
				object obj = ResourceManager.GetObject("network-idle", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap network_offline {
			get {
				object obj = ResourceManager.GetObject("network-offline", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap network_receive {
			get {
				object obj = ResourceManager.GetObject("network-receive", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap network_transmit {
			get {
				object obj = ResourceManager.GetObject("network-transmit", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap network_transmit_receive {
			get {
				object obj = ResourceManager.GetObject("network-transmit-receive", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap network_wireless_encrypted {
			get {
				object obj = ResourceManager.GetObject("network-wireless-encrypted", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap printer_error {
			get {
				object obj = ResourceManager.GetObject("printer-error", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap software_update_available {
			get {
				object obj = ResourceManager.GetObject("software-update-available", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap software_update_urgent {
			get {
				object obj = ResourceManager.GetObject("software-update-urgent", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap user_trash_full {
			get {
				object obj = ResourceManager.GetObject("user-trash-full", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap weather_clear {
			get {
				object obj = ResourceManager.GetObject("weather-clear", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap weather_clear_night {
			get {
				object obj = ResourceManager.GetObject("weather-clear-night", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap weather_few_clouds {
			get {
				object obj = ResourceManager.GetObject("weather-few-clouds", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap weather_few_clouds_night {
			get {
				object obj = ResourceManager.GetObject("weather-few-clouds-night", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap weather_overcast {
			get {
				object obj = ResourceManager.GetObject("weather-overcast", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap weather_severe_alert {
			get {
				object obj = ResourceManager.GetObject("weather-severe-alert", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap weather_showers {
			get {
				object obj = ResourceManager.GetObject("weather-showers", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap weather_showers_scattered {
			get {
				object obj = ResourceManager.GetObject("weather-showers-scattered", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap weather_snow {
			get {
				object obj = ResourceManager.GetObject("weather-snow", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap weather_storm {
			get {
				object obj = ResourceManager.GetObject("weather-storm", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
