//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fam3 {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class tango_emotes {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal tango_emotes() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fam3.tango_emotes", typeof(tango_emotes).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		public static System.Drawing.Bitmap face_angel {
			get {
				object obj = ResourceManager.GetObject("face-angel", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap face_crying {
			get {
				object obj = ResourceManager.GetObject("face-crying", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap face_devilish {
			get {
				object obj = ResourceManager.GetObject("face-devilish", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap face_glasses {
			get {
				object obj = ResourceManager.GetObject("face-glasses", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap face_grin {
			get {
				object obj = ResourceManager.GetObject("face-grin", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap face_kiss {
			get {
				object obj = ResourceManager.GetObject("face-kiss", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap face_monkey {
			get {
				object obj = ResourceManager.GetObject("face-monkey", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap face_plain {
			get {
				object obj = ResourceManager.GetObject("face-plain", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap face_sad {
			get {
				object obj = ResourceManager.GetObject("face-sad", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap face_smile {
			get {
				object obj = ResourceManager.GetObject("face-smile", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap face_smile_big {
			get {
				object obj = ResourceManager.GetObject("face-smile-big", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap face_surprise {
			get {
				object obj = ResourceManager.GetObject("face-surprise", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap face_wink {
			get {
				object obj = ResourceManager.GetObject("face-wink", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
