//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fam3 {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class tango_places {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal tango_places() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fam3.tango_places", typeof(tango_places).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		public static System.Drawing.Bitmap folder {
			get {
				object obj = ResourceManager.GetObject("folder", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_remote {
			get {
				object obj = ResourceManager.GetObject("folder-remote", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_saved_search {
			get {
				object obj = ResourceManager.GetObject("folder-saved-search", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap network_server {
			get {
				object obj = ResourceManager.GetObject("network-server", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap network_workgroup {
			get {
				object obj = ResourceManager.GetObject("network-workgroup", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap start_here {
			get {
				object obj = ResourceManager.GetObject("start-here", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap user_desktop {
			get {
				object obj = ResourceManager.GetObject("user-desktop", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap user_home {
			get {
				object obj = ResourceManager.GetObject("user-home", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap user_trash {
			get {
				object obj = ResourceManager.GetObject("user-trash", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
