//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fam3 {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class tango_actions {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal tango_actions() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fam3.tango_actions", typeof(tango_actions).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		public static System.Drawing.Bitmap address_book_new {
			get {
				object obj = ResourceManager.GetObject("address-book-new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap appointment_new {
			get {
				object obj = ResourceManager.GetObject("appointment-new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap bookmark_new {
			get {
				object obj = ResourceManager.GetObject("bookmark-new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap contact_new {
			get {
				object obj = ResourceManager.GetObject("contact-new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_new {
			get {
				object obj = ResourceManager.GetObject("document-new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_open {
			get {
				object obj = ResourceManager.GetObject("document-open", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_print {
			get {
				object obj = ResourceManager.GetObject("document-print", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_print_preview {
			get {
				object obj = ResourceManager.GetObject("document-print-preview", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_properties {
			get {
				object obj = ResourceManager.GetObject("document-properties", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_save {
			get {
				object obj = ResourceManager.GetObject("document-save", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap document_save_as {
			get {
				object obj = ResourceManager.GetObject("document-save-as", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap edit_clear {
			get {
				object obj = ResourceManager.GetObject("edit-clear", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap edit_copy {
			get {
				object obj = ResourceManager.GetObject("edit-copy", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap edit_cut {
			get {
				object obj = ResourceManager.GetObject("edit-cut", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap edit_delete {
			get {
				object obj = ResourceManager.GetObject("edit-delete", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap edit_find {
			get {
				object obj = ResourceManager.GetObject("edit-find", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap edit_find_replace {
			get {
				object obj = ResourceManager.GetObject("edit-find-replace", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap edit_paste {
			get {
				object obj = ResourceManager.GetObject("edit-paste", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap edit_redo {
			get {
				object obj = ResourceManager.GetObject("edit-redo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap edit_select_all {
			get {
				object obj = ResourceManager.GetObject("edit-select-all", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap edit_undo {
			get {
				object obj = ResourceManager.GetObject("edit-undo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap folder_new {
			get {
				object obj = ResourceManager.GetObject("folder-new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap format_indent_less {
			get {
				object obj = ResourceManager.GetObject("format-indent-less", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap format_indent_more {
			get {
				object obj = ResourceManager.GetObject("format-indent-more", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap format_justify_center {
			get {
				object obj = ResourceManager.GetObject("format-justify-center", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap format_justify_fill {
			get {
				object obj = ResourceManager.GetObject("format-justify-fill", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap format_justify_left {
			get {
				object obj = ResourceManager.GetObject("format-justify-left", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap format_justify_right {
			get {
				object obj = ResourceManager.GetObject("format-justify-right", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap format_text_bold {
			get {
				object obj = ResourceManager.GetObject("format-text-bold", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap format_text_italic {
			get {
				object obj = ResourceManager.GetObject("format-text-italic", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap format_text_strikethrough {
			get {
				object obj = ResourceManager.GetObject("format-text-strikethrough", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap format_text_underline {
			get {
				object obj = ResourceManager.GetObject("format-text-underline", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap go_bottom {
			get {
				object obj = ResourceManager.GetObject("go-bottom", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap go_down {
			get {
				object obj = ResourceManager.GetObject("go-down", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap go_first {
			get {
				object obj = ResourceManager.GetObject("go-first", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap go_home {
			get {
				object obj = ResourceManager.GetObject("go-home", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap go_jump {
			get {
				object obj = ResourceManager.GetObject("go-jump", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap go_last {
			get {
				object obj = ResourceManager.GetObject("go-last", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap go_next {
			get {
				object obj = ResourceManager.GetObject("go-next", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap go_previous {
			get {
				object obj = ResourceManager.GetObject("go-previous", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap go_top {
			get {
				object obj = ResourceManager.GetObject("go-top", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap go_up {
			get {
				object obj = ResourceManager.GetObject("go-up", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap list_add {
			get {
				object obj = ResourceManager.GetObject("list-add", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap list_remove {
			get {
				object obj = ResourceManager.GetObject("list-remove", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap mail_forward {
			get {
				object obj = ResourceManager.GetObject("mail-forward", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap mail_mark_junk {
			get {
				object obj = ResourceManager.GetObject("mail-mark-junk", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap mail_mark_not_junk {
			get {
				object obj = ResourceManager.GetObject("mail-mark-not-junk", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap mail_message_new {
			get {
				object obj = ResourceManager.GetObject("mail-message-new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap mail_reply_all {
			get {
				object obj = ResourceManager.GetObject("mail-reply-all", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap mail_reply_sender {
			get {
				object obj = ResourceManager.GetObject("mail-reply-sender", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap mail_send_receive {
			get {
				object obj = ResourceManager.GetObject("mail-send-receive", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap media_eject {
			get {
				object obj = ResourceManager.GetObject("media-eject", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap media_playback_pause {
			get {
				object obj = ResourceManager.GetObject("media-playback-pause", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap media_playback_start {
			get {
				object obj = ResourceManager.GetObject("media-playback-start", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap media_playback_stop {
			get {
				object obj = ResourceManager.GetObject("media-playback-stop", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap media_record {
			get {
				object obj = ResourceManager.GetObject("media-record", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap media_seek_backward {
			get {
				object obj = ResourceManager.GetObject("media-seek-backward", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap media_seek_forward {
			get {
				object obj = ResourceManager.GetObject("media-seek-forward", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap media_skip_backward {
			get {
				object obj = ResourceManager.GetObject("media-skip-backward", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap media_skip_forward {
			get {
				object obj = ResourceManager.GetObject("media-skip-forward", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap process_stop {
			get {
				object obj = ResourceManager.GetObject("process-stop", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap system_lock_screen {
			get {
				object obj = ResourceManager.GetObject("system-lock-screen", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap system_log_out {
			get {
				object obj = ResourceManager.GetObject("system-log-out", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap system_search {
			get {
				object obj = ResourceManager.GetObject("system-search", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap system_shutdown {
			get {
				object obj = ResourceManager.GetObject("system-shutdown", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap tab_new {
			get {
				object obj = ResourceManager.GetObject("tab-new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap view_fullscreen {
			get {
				object obj = ResourceManager.GetObject("view-fullscreen", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap view_refresh {
			get {
				object obj = ResourceManager.GetObject("view-refresh", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap window_new {
			get {
				object obj = ResourceManager.GetObject("window-new", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
