//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fam3 {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class tango_apps {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal tango_apps() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fam3.tango_apps", typeof(tango_apps).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		public static System.Drawing.Bitmap accessories_calculator {
			get {
				object obj = ResourceManager.GetObject("accessories-calculator", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap accessories_character_map {
			get {
				object obj = ResourceManager.GetObject("accessories-character-map", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap accessories_text_editor {
			get {
				object obj = ResourceManager.GetObject("accessories-text-editor", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap help_browser {
			get {
				object obj = ResourceManager.GetObject("help-browser", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap internet_group_chat {
			get {
				object obj = ResourceManager.GetObject("internet-group-chat", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap internet_mail {
			get {
				object obj = ResourceManager.GetObject("internet-mail", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap internet_news_reader {
			get {
				object obj = ResourceManager.GetObject("internet-news-reader", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap internet_web_browser {
			get {
				object obj = ResourceManager.GetObject("internet-web-browser", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap office_calendar {
			get {
				object obj = ResourceManager.GetObject("office-calendar", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap preferences_desktop_accessibility {
			get {
				object obj = ResourceManager.GetObject("preferences-desktop-accessibility", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap preferences_desktop_assistive_technology {
			get {
				object obj = ResourceManager.GetObject("preferences-desktop-assistive-technology", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap preferences_desktop_font {
			get {
				object obj = ResourceManager.GetObject("preferences-desktop-font", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap preferences_desktop_keyboard_shortcuts {
			get {
				object obj = ResourceManager.GetObject("preferences-desktop-keyboard-shortcuts", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap preferences_desktop_locale {
			get {
				object obj = ResourceManager.GetObject("preferences-desktop-locale", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap preferences_desktop_multimedia {
			get {
				object obj = ResourceManager.GetObject("preferences-desktop-multimedia", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap preferences_desktop_remote_desktop {
			get {
				object obj = ResourceManager.GetObject("preferences-desktop-remote-desktop", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap preferences_desktop_screensaver {
			get {
				object obj = ResourceManager.GetObject("preferences-desktop-screensaver", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap preferences_desktop_theme {
			get {
				object obj = ResourceManager.GetObject("preferences-desktop-theme", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap preferences_desktop_wallpaper {
			get {
				object obj = ResourceManager.GetObject("preferences-desktop-wallpaper", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap preferences_system_network_proxy {
			get {
				object obj = ResourceManager.GetObject("preferences-system-network-proxy", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap preferences_system_session {
			get {
				object obj = ResourceManager.GetObject("preferences-system-session", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap preferences_system_windows {
			get {
				object obj = ResourceManager.GetObject("preferences-system-windows", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap system_file_manager {
			get {
				object obj = ResourceManager.GetObject("system-file-manager", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap system_installer {
			get {
				object obj = ResourceManager.GetObject("system-installer", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap system_software_update {
			get {
				object obj = ResourceManager.GetObject("system-software-update", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap system_users {
			get {
				object obj = ResourceManager.GetObject("system-users", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap utilities_system_monitor {
			get {
				object obj = ResourceManager.GetObject("utilities-system-monitor", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		public static System.Drawing.Bitmap utilities_terminal {
			get {
				object obj = ResourceManager.GetObject("utilities-terminal", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
